CREATE DATABASE IF NOT EXISTS elpyand_portfolio;

USE elpyand_portfolio;

CREATE TABLE IF NOT EXISTS kontak (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    hp VARCHAR(15) NOT NULL,
    pesan VARCHAR(250) NOT NULL,
    tanggal TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);